import assert from 'node:assert/strict';
import test from 'node:test';

import { createAppointmentScheduler } from '../appointment-scheduler.service.js';

function row(overrides: Record<string, unknown> = {}): any { return { id: 'a', projectId: 'p', sessionId: 's', userId: 'u', provider: 'opencode', prompt: 'go', options: {}, attachments: [], triggerType: 'exact', dueAt: 1_000, timerDurationMs: null, projectIdleSince: null, queuePosition: null, runGeneration: null, isActive: true, status: 'scheduled', errorMessage: null, createdAt: 0, updatedAt: 0, claimedAt: null, completedAt: null, ...overrides }; }
function setup(initial: any[], overrides: Record<string, unknown> = {}) {
  let now = 1_000; const rows = initial; const starts: any[] = []; let quarantined = 0;
  const appointments = { listDue: () => rows.filter((r) => r.status === 'scheduled' && ['exact', 'timer'].includes(r.triggerType) && r.dueAt <= now), listProjectIdle: () => rows.filter((r) => r.status === 'scheduled' && r.triggerType === 'project_idle'), listNextQueued: () => rows.filter((r) => r.status === 'scheduled' && r.triggerType === 'queue').sort((a, b) => a.queuePosition - b.queuePosition).filter((r, index, all) => all.findIndex((entry) => entry.projectId === r.projectId) === index), listRunning: () => rows.filter((r) => r.status === 'running'), markActiveProjectIdleNeedsReview: () => { quarantined += 1; for (const r of rows) if (r.triggerType === 'project_idle' && r.status === 'scheduled') r.status = 'needs_review'; return 1; }, activateDraftForDispatch: (id: string, projectId: string, userId: string) => { const r = rows.find((x) => x.id === id && x.projectId === projectId && x.userId === userId && x.status === 'draft' && x.triggerType === 'queue'); if (!r) return null; r.status = 'scheduled'; r.isActive = true; return r; }, claim: (id: string) => { const r = rows.find((x) => x.id === id && x.status === 'scheduled'); if (!r) return null; r.status = 'running'; return r; }, assignRunGeneration: (id: string, generation: number) => { const r = rows.find((x) => x.id === id && x.status === 'running'); if (!r) return false; r.runGeneration = generation; return true; }, transition: (id: string, expected: string, next: string, _at: number, error: string | null) => { const r = rows.find((x) => x.id === id && x.status === expected); if (!r) return false; r.status = next; r.errorMessage = error; return true; }, update: (id: string, _p: string, _u: string, input: any) => { const r = rows.find((x) => x.id === id); Object.assign(r, input); return r; } };
  const scheduler = createAppointmentScheduler({ appointments, getSessionById: (id: string) => ({ project_path: id.startsWith('s2') ? '/p2' : '/p' }), getRunState: () => null, listRunningRuns: () => [], isProcessing: () => false, startRun: async (input: unknown) => { starts.push(input); return { generation: starts.length }; }, now: () => now, intervalMs: 10_000, idleQuiescenceMs: 100, ...overrides } as any);
  return { scheduler, starts, rows, setNow: (value: number) => { now = value; }, quarantined: () => quarantined };
}

test('due exact and timer rows record generations and remain running until durable completion', async () => { const rows = [row(), row({ id: 'timer', sessionId: 's2', triggerType: 'timer', timerDurationMs: 500 })]; let complete = false; const ctx = setup(rows, { getRunState: (id: string) => complete ? ({ sessionId: id, generation: id === 's' ? 1 : 2, lifecycleState: 'completed' }) : null }); await ctx.scheduler.tick(); assert.equal(ctx.starts.length, 2); assert.deepEqual(ctx.rows.map((r) => r.status), ['running', 'running']); complete = true; await ctx.scheduler.tick(); assert.deepEqual(ctx.rows.map((r) => r.status), ['completed', 'completed']); });
test('busy target sessions defer without claiming', async () => { const ctx = setup([row()], { isProcessing: () => true }); await ctx.scheduler.tick(); assert.equal(ctx.starts.length, 0); assert.equal(ctx.rows[0].status, 'scheduled'); });
test('project idle requires continuous quiescence and resets when project becomes busy', async () => { let busy = false; const ctx = setup([row({ triggerType: 'project_idle', dueAt: null })], { listRunningRuns: () => busy ? [{ sessionId: 'other' }] : [], getSessionById: () => ({ project_path: '/p' }) }); await ctx.scheduler.tick(); assert.equal(ctx.rows[0].projectIdleSince, 1_000); busy = true; ctx.setNow(1_050); await ctx.scheduler.tick(); assert.equal(ctx.rows[0].projectIdleSince, null); busy = false; await ctx.scheduler.tick(); ctx.setNow(1_151); await ctx.scheduler.tick(); assert.equal(ctx.starts.length, 1); });
test('startup quarantines project-idle rows, uses unref timer, and stop is safe', () => { const ctx = setup([row({ triggerType: 'project_idle' })]); ctx.scheduler.start(); assert.equal(ctx.quarantined(), 1); assert.equal(ctx.rows[0].status, 'needs_review'); ctx.scheduler.stop(); });
test('launch failures are recorded and untrusted attachments are removed', async () => { const ctx = setup([row({ attachments: [{ path: '/etc/passwd' }] })], { startRun: async () => { throw new Error('launch failed'); } }); await ctx.scheduler.tick(); assert.equal(ctx.rows[0].status, 'failed'); assert.equal(ctx.rows[0].errorMessage, 'launch failed'); });
test('queue dispatch is ordered and starts at most one row per project per tick', async () => { const ctx = setup([row({ id: 'q2', triggerType: 'queue', queuePosition: 2 }), row({ id: 'q1', triggerType: 'queue', queuePosition: 1 }), row({ id: 'other', projectId: 'p2', sessionId: 's2', triggerType: 'queue', queuePosition: 1 })]); await ctx.scheduler.tick(); assert.deepEqual(ctx.starts.map((entry) => entry.sessionId), ['s', 's2']); assert.equal(ctx.rows.find((entry) => entry.id === 'q2').status, 'scheduled'); });
test('non-running durable lifecycle outcomes do not block queue dispatch', async () => { for (const lifecycleState of ['stalled', 'failed', 'exited', 'manually_stopped', 'recovery_exhausted']) { const ctx = setup([row({ triggerType: 'queue', queuePosition: 1 })], { getRunState: () => ({ sessionId: 'other', desiredState: 'running', lifecycleState }) }); await ctx.scheduler.tick(); assert.equal(ctx.starts.length, 1, lifecycleState); } });
test('live runs and running appointments block a second project dispatch', async () => { const live = setup([row({ triggerType: 'queue', queuePosition: 1 })], { listRunningRuns: () => [{ sessionId: 'other' }] }); await live.scheduler.tick(); assert.equal(live.starts.length, 0); const running = setup([row({ id: 'active', sessionId: 'other', status: 'running' }), row({ id: 'queued', triggerType: 'queue', queuePosition: 1 })]); await running.scheduler.tick(); assert.equal(running.starts.length, 0); assert.equal(running.rows[1].status, 'scheduled'); });
test('matching terminal generations reconcile and release the next queued prompt', async () => { for (const lifecycleState of ['stalled', 'failed', 'exited', 'manually_stopped', 'recovery_exhausted', 'completed']) { const active = row({ id: 'active', status: 'running', runGeneration: 7 }); const queued = row({ id: 'queued', triggerType: 'queue', queuePosition: 1 }); const ctx = setup([active, queued], { getRunState: () => ({ sessionId: 's', generation: 7, lifecycleState, terminalMessage: `${lifecycleState} message` }) }); await ctx.scheduler.tick(); assert.equal(active.status, lifecycleState === 'completed' ? 'completed' : 'failed', lifecycleState); assert.equal(queued.status, 'running', lifecycleState); } });
test('generation mismatch cannot finalize or unblock the running appointment', async () => { const active = row({ id: 'active', status: 'running', runGeneration: 7 }); const queued = row({ id: 'queued', triggerType: 'queue', queuePosition: 1 }); const ctx = setup([active, queued], { getRunState: () => ({ sessionId: 's', generation: 8, lifecycleState: 'completed' }) }); await ctx.scheduler.tick(); assert.equal(active.status, 'running'); assert.equal(queued.status, 'scheduled'); assert.equal(ctx.starts.length, 0); });
test('queue dispatch forwards the exact stored prompt', async () => { const prompt = 'Exact queued prompt\nwith punctuation: [] & spaces  '; const ctx = setup([row({ triggerType: 'queue', queuePosition: 1, prompt })]); await ctx.scheduler.tick(); assert.equal(ctx.starts[0]?.command, prompt); });
test('manual dispatch targets a non-head draft and forwards payload with generation', async () => { const target = row({ id: 'q2', triggerType: 'queue', queuePosition: 2, status: 'draft', isActive: false, prompt: 'target', options: { model: 'm' } }); const ctx = setup([row({ id: 'q1', triggerType: 'queue', queuePosition: 1 }), target]); assert.equal(await ctx.scheduler.dispatchNow(target), 'started'); assert.equal(ctx.rows[0].status, 'scheduled'); assert.equal(target.status, 'running'); assert.equal(target.runGeneration, 1); assert.equal(ctx.starts[0].command, 'target'); assert.equal(ctx.starts[0].options.model, 'm'); });
test('manual dispatch rejects busy projects, processing sessions, and lost claims', async () => { const busyRow = row({ triggerType: 'queue' }); const busy = setup([busyRow], { listRunningRuns: () => [{ sessionId: 'other' }] }); assert.equal(await busy.scheduler.dispatchNow(busyRow), 'project_busy'); const processing = setup([row({ triggerType: 'queue' })], { isProcessing: () => true }); assert.equal(await processing.scheduler.dispatchNow(processing.rows[0]), 'session_busy'); const stale = setup([row({ triggerType: 'queue' })]); stale.rows[0].status = 'cancelled'; assert.equal(await stale.scheduler.dispatchNow({ ...stale.rows[0], status: 'scheduled' }), 'stale'); });
